#!/usr/bin/env bash
# numbers from 1 to 20.

for ((COUNTER = 1; COUNTER <= 20; COUNTER++)); do
    case $COUNTER in
        4)  echo "$COUNTER bad luck from China" ;;
        9)  echo "$COUNTER bad luck from Japan" ;;
        17) echo "$COUNTER bad luck from Italy" ;;
        *)  echo $COUNTER ;;
    esac
done
